"""The closed file list of one submission (plan §6.1).

The packer never copies ``topics/<id>/`` wholesale: the directory holds historical runs,
previews, staging and whatever else the contributor's machine accumulated.  The closed
list is *computed* from the page run's manifest pins, and the same computation runs on
both sides — at pack time over the contributor's tree, at G1 over the imported archive —
so "the archive contains exactly its closure" is checked, not assumed.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Iterable, Optional

from newsab_schema.artifacts import load_manifest
from newsab_schema.io import ArtifactError
from newsab_schema.models.corpus import CorpusRun, article_content_hash
from newsab_schema.models.manifest import ManifestEntry
from newsab_schema.paths import TopicPaths
from newsab_schema.store import read_article

from .envelope import REGISTRY_MEMBER, TOPIC_ROOT

#: File suffixes the archive refuses to carry as bytes; closure files matching them are
#: recorded hash-only and rebuilt by the site's own trusted renderer (plan §6.1).
#: Re-exported: the protocol fact lives with the fingerprint code that honours it, so the
#: packer and the trusted loader cannot drift apart on what may travel by hash.
from newsab_schema.artifacts import HASH_ONLY_SUFFIXES  # noqa: E402,F401

#: The only file names a corpus run directory may contribute.  Unlike every other pinned
#: stage, a corpus run's fingerprint is its article ``set_hash``, so the directory digest
#: does not cover stray files — the member list must be closed by name instead.
CORPUS_RUN_FILES = ("corpus_run.json", "index.jsonl")

#: Small public-safe corpus-level render inputs and provenance files that may accompany
#: the closure.  ``topics_by_article.json`` carries the canonical mapping the reader page
#: displays (derived at pack time — its private staging inputs never enter the archive);
#: the collection log and withdrawal record are provenance the plan names explicitly.
OPTIONAL_CORPUS_FILES = (
    "topics_by_article.json",
    "collection_log.jsonl",
    "withdrawn.jsonl",
)


def sha256_bytes(payload: bytes) -> str:
    return f"sha256:{hashlib.sha256(payload).hexdigest()}"


@dataclass(frozen=True)
class PlannedMember:
    """One closed-list entry: where it goes in the archive and where its bytes are."""

    archive_path: str
    kind: str  # "included" | "hash_only"
    source: Optional[Path]  # None when payload carries generated bytes
    payload: Optional[bytes] = None

    def read(self) -> bytes:
        if self.payload is not None:
            return self.payload
        assert self.source is not None
        return self.source.read_bytes()


def topic_member(relative: str | PurePosixPath) -> str:
    return f"{TOPIC_ROOT}/{PurePosixPath(relative)}"


def ancestor_entries(entries: Iterable[ManifestEntry], page_run_id: str) -> list[ManifestEntry]:
    """The page run's manifest entry plus its full upstream cone, in original order.

    The subset is transitively closed by construction: every ``inputs`` edge of every
    kept entry points at another kept entry, so an importer can re-walk the same
    ancestry the contributor's manifest proved.
    """
    by_id = {entry.run_id: entry for entry in entries}
    if page_run_id not in by_id:
        raise ArtifactError(f"page run is absent from topic manifest: {page_run_id}")
    keep: set[str] = set()
    pending = [page_run_id]
    while pending:
        current = pending.pop()
        if current in keep:
            continue
        keep.add(current)
        entry = by_id.get(current)
        if entry is not None:
            pending.extend(entry.inputs)
    return [entry for entry in entries if entry.run_id in keep]


def manifest_subset_bytes(paths: TopicPaths, page_run_id: str) -> bytes:
    """The archived manifest: the ancestor entries' original lines, verbatim."""
    keep = {entry.run_id for entry in ancestor_entries(load_manifest(paths), page_run_id)}
    lines = []
    for line in paths.manifest.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        entry = ManifestEntry.model_validate_json(line)
        if entry.run_id in keep:
            lines.append(line)
    return ("\n".join(lines) + "\n").encode("utf-8")


def article_source_file(paths: TopicPaths, article_id: str, content_hash: str) -> Path:
    """The on-disk file whose *content* matches the pinned hash — current or superseded.

    The archive stores it at the canonical current-store path either way: in the fresh
    import namespace it becomes the store's only version, and the pinned content hash is
    what every verifier checks.
    """
    current = paths.article_file(article_id)
    if current.is_file() and article_content_hash(read_article(current)) == content_hash:
        return current
    superseded = paths.superseded_articles_dir
    if superseded.is_dir():
        for candidate in sorted(superseded.glob(f"{article_id}.*.json")):
            if article_content_hash(read_article(candidate)) == content_hash:
                return candidate
    raise ArtifactError(
        f"{article_id}: pinned content {content_hash} is not in the store "
        "(neither current nor superseded)"
    )


def run_dir_members(paths: TopicPaths, stage: str, run_id: str) -> list[PlannedMember]:
    """Every file of one pinned run directory, previews demoted to hash-only."""
    run_dir = (
        paths.a1_run_dir(run_id) if stage == "analysis" else paths.stage_run_dir(stage, run_id)
    )
    if not run_dir.is_dir():
        raise ArtifactError(f"pinned {stage} run directory is missing: {run_dir}")
    members: list[PlannedMember] = []
    for file in sorted(path for path in run_dir.rglob("*") if path.is_file()):
        if file.is_symlink():
            raise ArtifactError(f"run directory contains a symlink: {file}")
        relative = file.relative_to(paths.root).as_posix()
        if stage == "corpus" and file.name not in CORPUS_RUN_FILES:
            raise ArtifactError(
                f"corpus run directory holds an unexpected file: {relative} "
                f"(allowed: {', '.join(CORPUS_RUN_FILES)})"
            )
        kind = (
            "hash_only"
            if file.suffix.lower() in HASH_ONLY_SUFFIXES
            else "included"
        )
        members.append(PlannedMember(topic_member(relative), kind, file))
    if not members:
        raise ArtifactError(f"pinned {stage} run directory is empty: {run_dir}")
    return members


def plan_members(
    paths: TopicPaths,
    corpus_run: CorpusRun,
    stage_runs: dict[str, str],
    *,
    manifest_bytes: bytes,
    topics_by_article_bytes: bytes,
    registry_bytes: bytes,
) -> list[PlannedMember]:
    """The full closed list for a create archive, sorted by archive path.

    ``stage_runs`` maps the six versioned logical stages (corpus, questions, answers,
    normalization, analysis, page) to their pinned run ids; the scope pin travels as
    ``topic_manifest.yaml`` itself.
    """
    members: list[PlannedMember] = [
        PlannedMember(topic_member("topic_manifest.yaml"), "included", paths.topic_manifest),
        PlannedMember(
            topic_member("manifest/manifest.jsonl"), "included", None, manifest_bytes
        ),
    ]
    stage_dirs = {
        "corpus": "corpus",
        "questions": "questions",
        "answers": "answers",
        "normalization": "normalization",
        "analysis": "analysis",
        "page": "editorial",
    }
    for stage, run_id in stage_runs.items():
        members.extend(run_dir_members(paths, stage_dirs[stage], run_id))
    for member in corpus_run.articles:
        source = article_source_file(paths, member.article_id, member.content_hash)
        members.append(
            PlannedMember(
                topic_member(f"corpus/articles/{member.article_id}.json"),
                "included",
                source,
            )
        )
    if topics_by_article_bytes.strip() not in (b"", b"{}"):
        members.append(
            PlannedMember(
                topic_member("corpus/topics_by_article.json"),
                "included",
                None,
                topics_by_article_bytes,
            )
        )
    for optional in ("collection_log.jsonl", "withdrawn.jsonl"):
        candidate = paths.corpus_dir / optional
        if candidate.is_file():
            members.append(
                PlannedMember(topic_member(f"corpus/{optional}"), "included", candidate)
            )
    if registry_bytes.strip():
        members.append(PlannedMember(REGISTRY_MEMBER, "included", None, registry_bytes))
    members.sort(key=lambda member: member.archive_path)
    return members


def stage_dir_prefix(stage: str, run_id: str) -> str:
    """The archive path prefix one pinned stage's run directory occupies."""
    if stage == "analysis":
        return topic_member(f"analysis/{run_id}") + "/"
    directory = "editorial" if stage == "page" else stage
    return topic_member(f"{directory}/versions/{run_id}") + "/"
