"""Generate the language-neutral copies of this package's definitions.

Python is the definition site, but the frontend (TypeScript), a contributor's agent, and
anyone reading a skill reference all need the same enums and shapes.
Rather than let them retype the lists, this module emits them into ``dist/``:

* ``dist/enums.json``    — every controlled vocabulary, machine readable;
* ``dist/enums.md``      — the same, as a table skills can link to instead of copying;
* ``dist/*.schema.json`` — JSON Schema for each record type.

``tests/test_export_and_io.py::test_dist_is_not_stale`` regenerates and diffs, so a stale
``dist/`` fails CI rather than quietly serving an old vocabulary to a contributor.  The diff
is *semantic*, not byte-exact: see ``check_in_sync``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from . import enums as enums_module
from .models import SCHEMA_STATUS
from .models.analysis import CandidateAngle, Claim
from .models.annotation import ArticleAnnotation, ConceptOntology, Observation
from .models.corpus import Article, CorpusRun, SourceRegistry, TopicManifest
from .models.editorial import AngleCard, EditorialPage
from .models.gold import GoldStandardSet
from .models.manifest import CorrectionMapping, ManifestEntry
from .models.category_map import CategoryMap
from .models.findings import QAFinding
from .models.page import ReaderPage
from .models.qa import ClusterAnswer, QuestionSet
from .models.publication import CatalogRecord, PublicationEvent, PublicationRecord, PublishSelector

DIST = Path(__file__).parent.parent / "dist"

GENERATED_HEADER = (
    "GENERATED by newsab_schema.export — do not edit. "
    "Definition site: packages/schema/newsab_schema/"
)

EXPORTED_MODELS = {
    "question_set": QuestionSet,
    "cluster_answer": ClusterAnswer,
    "category_map": CategoryMap,
    "qa_finding": QAFinding,
    "reader_page": ReaderPage,
    "observation": Observation,
    "article_annotation": ArticleAnnotation,
    "concept_ontology": ConceptOntology,
    "candidate_angle": CandidateAngle,
    "claim": Claim,
    "angle_card": AngleCard,
    "editorial_page": EditorialPage,
    "topic_manifest": TopicManifest,
    "source_registry": SourceRegistry,
    "article": Article,
    "corpus_run": CorpusRun,
    "gold_standard_set": GoldStandardSet,
    "manifest_entry": ManifestEntry,
    "correction_mapping": CorrectionMapping,
    "publication_record": PublicationRecord,
    "publication_event": PublicationEvent,
    "catalog_record": CatalogRecord,
    "publish_selector": PublishSelector,
}


def enums_payload() -> dict[str, Any]:
    """Every controlled vocabulary, tagged with whether §4.1 locks it."""
    return {
        "_generated": GENERATED_HEADER,
        "locked_by_blueprint_4_1": sorted(enums_module.LOCKED),
        "enums": {
            name: {
                "values": cls.values(),
                "locked": name in enums_module.LOCKED,
                "doc": (cls.__doc__ or "").strip().splitlines()[0] if cls.__doc__ else "",
            }
            for name, cls in sorted(enums_module.ALL.items())
        },
        "required_attrs_by_dimension": {
            dim.value: list(keys) for dim, keys in enums_module.REQUIRED_ATTRS.items()
        },
        "angle_type_dimensions": {
            at.value: [d.value for d in dims]
            for at, dims in enums_module.ANGLE_TYPE_DIMENSIONS.items()
        },
        "e_score_axes": list(enums_module.E_SCORE_AXES),
        "human_score_axes": list(enums_module.HUMAN_SCORE_AXES),
    }


def enums_markdown() -> str:
    payload = enums_payload()
    lines = [
        f"<!-- {GENERATED_HEADER} -->",
        "",
        "# Controlled vocabularies",
        "",
        "Link to this file from a skill; never copy the values into prose — a second copy",
        "is a second thing to keep in sync, and blueprint §4.1 allows exactly one.",
        "",
        "| vocabulary | locked by §4.1 | values |",
        "|---|---|---|",
    ]
    for name, meta in payload["enums"].items():
        lock = "yes" if meta["locked"] else "no (draft schema, §4.6)"
        lines.append(f"| `{name}` | {lock} | {', '.join(f'`{v}`' for v in meta['values'])} |")
    lines += [
        "",
        "## Required `attrs` per dimension (§4.2.1)",
        "",
        "| dimension | required attrs |",
        "|---|---|",
    ]
    for dim, keys in payload["required_attrs_by_dimension"].items():
        lines.append(f"| `{dim}` | {', '.join(f'`{k}`' for k in keys) if keys else '—'} |")
    lines += [
        "",
        "## Score axes",
        "",
        f"- E-score (S6, 0–2 each): {', '.join(f'`{a}`' for a in payload['e_score_axes'])}",
        f"- Human score (⑤, 1–5 each): {', '.join(f'`{a}`' for a in payload['human_score_axes'])}",
        "",
    ]
    return "\n".join(lines)


def json_schema_for(name: str) -> dict[str, Any]:
    model = EXPORTED_MODELS[name]
    schema = model.model_json_schema(mode="serialization")
    section, status = SCHEMA_STATUS.get(model.__name__, ("", "draft"))
    schema["$comment"] = f"{GENERATED_HEADER} | blueprint {section} | status: {status}"
    return schema


def write_all(dist: Path | str = DIST) -> list[Path]:
    """Regenerate ``dist/``.  Returns the files written."""
    out = Path(dist)
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    enums_path = out / "enums.json"
    enums_path.write_text(
        json.dumps(enums_payload(), ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    written.append(enums_path)

    md_path = out / "enums.md"
    md_path.write_text(enums_markdown(), encoding="utf-8")
    written.append(md_path)

    for name in sorted(EXPORTED_MODELS):
        path = out / f"{name}.schema.json"
        path.write_text(
            json.dumps(json_schema_for(name), ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        written.append(path)

    return written


def _canonical(node: Any) -> Any:
    """A JSON Schema fragment in one form, whichever form the generator emitted.

    Pydantic 2.9 changed how it emits a ``$ref`` that carries sibling keywords: before,
    the ref was wrapped in a single-element ``allOf``; since, it sits inline.  The two are
    the same schema, so a byte-exact diff would fail the gate for every contributor whose
    pydantic minor differs from the one that last wrote ``dist/`` — the exact class of
    unpassable gate that ``--scope workspace`` exists to avoid.  Normalize to the inline
    form before comparing; a real model change still differs.
    """
    if isinstance(node, dict):
        out = {key: _canonical(value) for key, value in node.items()}
        wrapped = out.get("allOf")
        if (
            isinstance(wrapped, list)
            and len(wrapped) == 1
            and isinstance(wrapped[0], dict)
            and list(wrapped[0]) == ["$ref"]
            and "$ref" not in out
        ):
            del out["allOf"]
            out["$ref"] = wrapped[0]["$ref"]
        return out
    if isinstance(node, list):
        return [_canonical(item) for item in node]
    return node


def _same_schema(generated: str, on_disk: str) -> bool:
    """True when two generated JSON documents mean the same thing."""
    if generated == on_disk:
        return True
    try:
        return _canonical(json.loads(generated)) == _canonical(json.loads(on_disk))
    except ValueError:
        return False


def check_in_sync(dist: Path | str = DIST) -> list[str]:
    """Names of generated files whose content differs from a fresh generation.

    JSON files are compared as canonicalized documents (``_canonical``); ``enums.md`` and
    anything unparseable is compared byte for byte.
    """
    out = Path(dist)
    stale: list[str] = []

    expected: dict[str, str] = {
        "enums.json": json.dumps(enums_payload(), ensure_ascii=False, indent=2, sort_keys=True)
        + "\n",
        "enums.md": enums_markdown(),
    }
    for name in EXPORTED_MODELS:
        expected[f"{name}.schema.json"] = (
            json.dumps(json_schema_for(name), ensure_ascii=False, indent=2, sort_keys=True) + "\n"
        )

    for filename, content in expected.items():
        path = out / filename
        if not path.exists():
            stale.append(filename)
            continue
        found = path.read_text(encoding="utf-8")
        same = _same_schema(content, found) if filename.endswith(".json") else found == content
        if not same:
            stale.append(filename)
    return sorted(stale)


if __name__ == "__main__":  # pragma: no cover
    for path in write_all():
        print(path)
