"""The dev-shell dashboard's own UI copy, in the halo's nine languages.

Distinct from ``site_strings.py`` (the reader-facing production site) and from each
topic's ``review_locale`` (the language that topic's touchpoint two is read and signed
in, which its manifest names and which the language button never moves).  This table is
purely cosmetic: which language the *tool* speaks to whoever is sitting at the keyboard,
chosen with the top-right language button and remembered in that browser's
``localStorage``.

Same pattern as ``site_strings.py``: a symmetric ``dict[locale, dict[key, str]]`` asserted
at import time, keyed by ``newsab_schema.HALO_LOCALES`` (the nine-language commitment the
home page's halo makes) rather than by ``SITE_LOCALES`` — the dashboard never had a
"live languages" gate to respect, so it goes straight to the full set.

A handful of values carry inline HTML (``<code>``, ``<strong>``) because the dashboard's
renderer builds its cards with plain string interpolation, not a template engine; every
locale must keep the same tags in the same places, which is a case-by-case translation
concern rather than something this module can check for.
"""

from __future__ import annotations

from types import MappingProxyType
from typing import Mapping

from newsab_schema import HALO_LOCALE_CODES
from newsab_schema.common import normalize_lang

#: The dashboard's own default UI language, independent of any topic's ``review_locale``
#: (which is approval semantics, not display, and comes from that topic's manifest
#: regardless of what a visitor's browser is showing).  It happens to match this
#: operator's language today because one person has ever opened this dashboard;
#: a visitor choosing another language via the button changes only this
#: one, and a clone whose operator reads something else changes only this line.
DEFAULT_DASHBOARD_LOCALE = "zh-CN"

_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "section_production": "1 · Production site",
        "section_scope": "2 · Topic scopes awaiting review (touchpoint one)",
        "section_release": "3 · Releases awaiting approval (touchpoint two)",
        "section_panels": "4 · Local private panels",
        "open_production": "Open the production site ↗",
        "topic_count_page_count": "{topics} topics · {pages} pages",
        "build_date": "Built {value}",
        "chrome_version": "chrome {value}",
        "production_missing": "The production tree does not exist yet; rebuild it per packages/publish/README.md.",
        "release_empty": "No candidates are waiting for approval. Render one with <code>review-preview</code>, then mount it with <code>dev-serve --preview &lt;dir&gt;</code>.",
        "release_none_pending": "No candidates are waiting for a decision.",
        "approve_all": "Approve and authorize all {n} at once…",
        "approve_all_hint": "The same reason is written for every one; use each card's own button to decide them individually.",
        "approve_all_confirm_prefix": "This will write the two records above once for each of: ",
        "reason_placeholder_each": "Reason (required — kept permanently with the event)",
        "reason_placeholder_all": "Reason (required — kept permanently with every event)",
        "confirm_all": "Confirm all",
        "cancel": "Cancel",
        "tag_live": "Live",
        "release_live_note": "This preview's bytes are already the live bytes; there is nothing to decide. Live version {publication_id}.",
        "release_no_review_locale": "This topic's <code>topic_manifest.yaml</code> names no review language, so there is no rendering an approval could be keyed to. Set <code>review_locale</code> in the scope, then reload.",
        "release_review_locale_absent": "This preview carries no {locale} page — the language this topic is reviewed in. Re-render the candidate in that language before approving.",
        "target_supersede": "replace the current live version {publication_id}",
        "target_first": "become this topic's <strong>first</strong> live version",
        "done_title": "Approved and authorized to ship",
        "done_record_label": "Record",
        "done_hint": "What is left is mechanical: verify-candidate reproduces the bytes, then an agent runs activate. A failed verify bounces it automatically — nothing ships quietly.",
        "approve_release_btn": "Approve and authorize…",
        "write_note_btn": "Write a review note (not an approval)",
        "confirm_records": "Confirming writes <strong>two records</strong> at once: one <code>PublicationReview</code> per language (binding the exact bytes above), and one <code>HumanApproval</code> authorizing this candidate to ",
        "confirm_kept_history": "The old version is not deleted — it becomes history; the event chain records this replacement.",
        "confirm_not_immediate": "<strong>Still not published on the spot</strong>: the candidate must first pass <code>verify-candidate</code>'s re-render comparison — any mismatched byte bounces it automatically.",
        "confirm_approve_btn": "Confirm approve and authorize",
        "new_page": "New page",
        "diff_from_live": "Differs from live",
        "same_as_live": "Same as live",
        "bytes_approved": "Bytes approved",
        "read_locale_link": "Read {locale} ↗",
        "candidate_hash_label": "candidate {hash}",
        "live_hash_label": "live {hash}",
        "page_run_label": "page run {value}",
        "theme_label": "theme {value}",
        "theme_none": "—",
        "categories_label": "categories {value}",
        "categories_none": "none proposed",
        "prepared_label": "prepared {id}",
        "not_prepared_label": "not yet prepared",
        "tag_unsigned": "Awaiting signature",
        "sign_in_browser_btn": "Sign touchpoint one in the browser",
        "scope_empty": "No topic scopes are waiting to be signed. ({n} already signed; signed ones are not listed.)",
        "scope_more_signed": "{n} more already signed, not listed.",
        "panels_hint": "Generated by a local script and visible only on this machine: never deployed, never committed, and not review bytes for any publication.",
        "form_groups": "The two groups",
        "form_include": "In scope",
        "form_exclude": "Out of scope",
        "form_seeds": "Question seeds",
        "form_required": "Required (annotate must cover it)",
        "form_note_placeholder": "Sign-off note (optional)",
        "form_submit": "Sign touchpoint one",
        "form_no_candidates": "This topic has no scope/question_candidates.yaml; signing only writes the manifest's scope_approval.",
        "form_window": "Window {start} → {end} · risk {risk}",
        "form_ongoing": "ongoing",
        "js_reason_required_each": "A reason is required: it is kept permanently with the event.",
        "js_reason_required_all": "A reason is required: it is kept permanently with every event.",
        "js_approved_authorized": "Approved and authorized {path}. Not published yet.",
        "js_not_approved": "Not approved: {error}",
        "js_authorized_n_failed_m": "Authorized {done}, failed {failed} — {detail}",
        "js_approved_all": "Approved and authorized {n}. Not published yet.",
        "js_note_prompt": "Review note / rejection reason (just a record — changes nothing):",
        "js_note_recorded": "Recorded {path}",
        "js_failed": "Failed: {error}",
        "js_scope_signed": "Touchpoint one is signed — reload to see it.",
        "js_scope_not_signed": "Not signed: {detail}",
        "theme_button_label": "Switch between light and dark mode",
        "language_button_label": "Switch interface language",
        "locale_plan_heading": "Also expand to these languages after approval",
        "locale_included_tag": "Included",
        "locale_plan_hint": "Checked languages are not reviewed here — a later localization run handles them under this same reason, without a second approval.",
    },
    "zh-CN": {
        "section_production": "一 · 生产站",
        "section_scope": "二 · 待审议题范围（触点一）",
        "section_release": "三 · 待批准上线（触点二）",
        "section_panels": "四 · 本机私有面板",
        "open_production": "打开生产站 ↗",
        "topic_count_page_count": "{topics} 个议题 · {pages} 个页面",
        "build_date": "构建日 {value}",
        "chrome_version": "chrome {value}",
        "production_missing": "生产树不存在；先按 packages/publish/README.md 重建。",
        "release_empty": "没有等待批准的候选。用 <code>review-preview</code> 渲一份，再用 <code>dev-serve --preview &lt;dir&gt;</code> 挂上来。",
        "release_none_pending": "没有待决定的候选。",
        "approve_all": "一次批准并授权全部 {n} 个…",
        "approve_all_hint": "同一个理由写给每一个；逐个决定就用下面各自的按钮。",
        "approve_all_confirm_prefix": "会对以下议题各写一遍上述两份记录：",
        "reason_placeholder_each": "理由（必填，会随事件永久留存）",
        "reason_placeholder_all": "理由（必填，会随每一个事件永久留存）",
        "confirm_all": "确认全部",
        "cancel": "取消",
        "tag_live": "已上线",
        "release_live_note": "这份预览的字节就是线上字节，没有待决定的事。线上版本 {publication_id}。",
        "release_no_review_locale": "该议题的 <code>topic_manifest.yaml</code> 没有写明审核语言，批准无从绑定到某一份渲染。请在 scope 里补上 <code>review_locale</code> 后刷新。",
        "release_review_locale_absent": "该预览没有 {locale} 页面——那是这个议题的审核语言。请先用该语言重新渲染候选件再批准。",
        "target_supersede": "替换当前线上版本 {publication_id}",
        "target_first": "成为该议题的<strong>第一个</strong>线上版本",
        "done_title": "已批准并授权上线",
        "done_record_label": "记录",
        "done_hint": "剩下的是机器的事：verify-candidate 复现字节，再由 agent 执行 activate。verify 不过就会自动打回，不会悄悄上线。",
        "approve_release_btn": "批准并授权上线…",
        "write_note_btn": "写审核意见（不批准）",
        "confirm_records": "点确认会一次写下<strong>两份记录</strong>：每个语言各一份 <code>PublicationReview</code>（绑定上面那几份精确字节），以及一份 <code>HumanApproval</code>，授权这份候选",
        "confirm_kept_history": "旧版本不会被删除，它变成历史；事件链记下这一次替换。",
        "confirm_not_immediate": "<strong>仍然不会当场发布</strong>：候选必须先通过 <code>verify-candidate</code> 的重渲比对，任何一个字节对不上都会被自动打回。",
        "confirm_approve_btn": "确认批准并授权",
        "new_page": "新页面",
        "diff_from_live": "与线上不同",
        "same_as_live": "与线上相同",
        "bytes_approved": "字节已批准",
        "read_locale_link": "读 {locale} ↗",
        "candidate_hash_label": "候选 {hash}",
        "live_hash_label": "线上 {hash}",
        "page_run_label": "page run {value}",
        "theme_label": "theme {value}",
        "theme_none": "—",
        "categories_label": "分类 {value}",
        "categories_none": "未提出",
        "prepared_label": "已 prepare {id}",
        "not_prepared_label": "尚未 prepare",
        "tag_unsigned": "待签署",
        "sign_in_browser_btn": "在浏览器里签署触点一",
        "scope_empty": "没有待签署的议题范围。（{n} 个已签署，签过的不再列出。）",
        "scope_more_signed": "另有 {n} 个已签署，不再列出。",
        "panels_hint": "由本机脚本生成，只在这台机器可见：不部署、不进 Git、不属于任何 publication 的审核字节。",
        "form_groups": "两组",
        "form_include": "范围内",
        "form_exclude": "范围外",
        "form_seeds": "问题种子",
        "form_required": "必答（annotate 必须覆盖）",
        "form_note_placeholder": "签署备注（可空）",
        "form_submit": "签署触点一",
        "form_no_candidates": "这个议题没有 scope/question_candidates.yaml；签署只写 manifest 的 scope_approval。",
        "form_window": "时间窗 {start} → {end} · 风险 {risk}",
        "form_ongoing": "进行中",
        "js_reason_required_each": "理由是必填的：它会随事件永久留存。",
        "js_reason_required_all": "理由是必填的：它会随每一个事件永久留存。",
        "js_approved_authorized": "已批准并授权 {path}。仍未发布。",
        "js_not_approved": "未批准：{error}",
        "js_authorized_n_failed_m": "已授权 {done} 个，失败 {failed} 个 — {detail}",
        "js_approved_all": "已批准并授权 {n} 个。仍未发布。",
        "js_note_prompt": "审核意见 / 驳回理由（只是记录，不改变任何状态）：",
        "js_note_recorded": "已记录 {path}",
        "js_failed": "失败：{error}",
        "js_scope_signed": "触点一已签署，刷新查看。",
        "js_scope_not_signed": "未签署：{detail}",
        "theme_button_label": "切换浅色 / 深色主题",
        "language_button_label": "切换界面语言",
        "locale_plan_heading": "批准后一并扩展到这些语言",
        "locale_included_tag": "已含",
        "locale_plan_hint": "勾选的语言这里不逐语审读——后续本地化流水线在同一个理由下补齐，不需要第二次批准。",
    },
    "ru": {
        "section_production": "1 · Продакшен-сайт",
        "section_scope": "2 · Темы, ожидающие проверки объёма (точка 1)",
        "section_release": "3 · Релизы, ожидающие одобрения (точка 2)",
        "section_panels": "4 · Локальные приватные панели",
        "open_production": "Открыть продакшен-сайт ↗",
        "topic_count_page_count": "{topics} тем · {pages} страниц",
        "build_date": "Сборка от {value}",
        "chrome_version": "chrome {value}",
        "production_missing": "Продакшен-дерево ещё не существует; пересоберите его по packages/publish/README.md.",
        "release_empty": "Нет кандидатов, ожидающих одобрения. Отрендерьте один командой <code>review-preview</code>, затем подключите его через <code>dev-serve --preview &lt;dir&gt;</code>.",
        "release_none_pending": "Нет кандидатов, ожидающих решения.",
        "approve_all": "Одобрить и авторизовать все {n} сразу…",
        "approve_all_hint": "Одна и та же причина будет записана для каждого; для решений по отдельности используйте кнопку на каждой карточке.",
        "approve_all_confirm_prefix": "Это запишет две записи выше для каждой из тем: ",
        "reason_placeholder_each": "Причина (обязательно — сохраняется вместе с событием навсегда)",
        "reason_placeholder_all": "Причина (обязательно — сохраняется вместе с каждым событием навсегда)",
        "confirm_all": "Подтвердить все",
        "cancel": "Отмена",
        "tag_live": "В эфире",
        "release_live_note": "Байты этого превью уже совпадают с байтами в эфире; решать нечего. Текущая версия в эфире {publication_id}.",
        "release_no_review_locale": "В <code>topic_manifest.yaml</code> этой темы не указан язык проверки, поэтому одобрение не к чему привязать. Укажите <code>review_locale</code> в scope и обновите страницу.",
        "release_review_locale_absent": "В этом предпросмотре нет страницы на {locale} — языке проверки этой темы. Перед одобрением перерендерьте кандидата на этом языке.",
        "target_supersede": "заменить текущую версию в эфире {publication_id}",
        "target_first": "стать <strong>первой</strong> версией этой темы в эфире",
        "done_title": "Одобрено и авторизовано к публикации",
        "done_record_label": "Запись",
        "done_hint": "Остальное — механика: verify-candidate воспроизводит байты, затем агент выполняет activate. Неудачная проверка автоматически отклоняет — ничего не публикуется незаметно.",
        "approve_release_btn": "Одобрить и авторизовать…",
        "write_note_btn": "Написать заметку рецензента (не одобрение)",
        "confirm_records": "Подтверждение сразу запишет <strong>две записи</strong>: по одному <code>PublicationReview</code> на язык (привязанному к точным байтам выше) и один <code>HumanApproval</code>, авторизующий этого кандидата ",
        "confirm_kept_history": "Старая версия не удаляется — она становится историей; цепочка событий фиксирует эту замену.",
        "confirm_not_immediate": "<strong>По-прежнему не публикуется на месте</strong>: кандидат должен сначала пройти повторное сравнение <code>verify-candidate</code> — любой несовпадающий байт отклонит его автоматически.",
        "confirm_approve_btn": "Подтвердить одобрение и авторизацию",
        "new_page": "Новая страница",
        "diff_from_live": "Отличается от версии в эфире",
        "same_as_live": "Совпадает с версией в эфире",
        "bytes_approved": "Байты одобрены",
        "read_locale_link": "Читать {locale} ↗",
        "candidate_hash_label": "кандидат {hash}",
        "live_hash_label": "в эфире {hash}",
        "page_run_label": "page run {value}",
        "theme_label": "тема {value}",
        "theme_none": "—",
        "categories_label": "категории {value}",
        "categories_none": "не предложены",
        "prepared_label": "подготовлено {id}",
        "not_prepared_label": "ещё не подготовлено",
        "tag_unsigned": "Ожидает подписи",
        "sign_in_browser_btn": "Подписать точку 1 в браузере",
        "scope_empty": "Нет тем, ожидающих подписи объёма. (Уже подписано {n}; подписанные не показываются.)",
        "scope_more_signed": "Ещё {n} уже подписаны, не показаны.",
        "panels_hint": "Сгенерировано локальным скриптом и видно только на этой машине: никогда не разворачивается, не коммитится и не является байтами проверки ни для одной публикации.",
        "form_groups": "Две группы",
        "form_include": "В рамках",
        "form_exclude": "Вне рамок",
        "form_seeds": "Исходные вопросы",
        "form_required": "Обязательно (annotate должен покрыть)",
        "form_note_placeholder": "Заметка при подписании (необязательно)",
        "form_submit": "Подписать точку 1",
        "form_no_candidates": "У этой темы нет scope/question_candidates.yaml; подписание запишет только scope_approval манифеста.",
        "form_window": "Период {start} → {end} · риск {risk}",
        "form_ongoing": "продолжается",
        "js_reason_required_each": "Причина обязательна: она сохраняется вместе с событием навсегда.",
        "js_reason_required_all": "Причина обязательна: она сохраняется вместе с каждым событием навсегда.",
        "js_approved_authorized": "Одобрено и авторизовано {path}. Ещё не опубликовано.",
        "js_not_approved": "Не одобрено: {error}",
        "js_authorized_n_failed_m": "Авторизовано {done}, не удалось {failed} — {detail}",
        "js_approved_all": "Одобрено и авторизовано {n}. Ещё не опубликовано.",
        "js_note_prompt": "Заметка рецензента / причина отклонения (это просто запись — ничего не меняет):",
        "js_note_recorded": "Записано {path}",
        "js_failed": "Ошибка: {error}",
        "js_scope_signed": "Точка 1 подписана — обновите страницу, чтобы увидеть.",
        "js_scope_not_signed": "Не подписано: {detail}",
        "theme_button_label": "Переключить светлую / тёмную тему",
        "language_button_label": "Переключить язык интерфейса",
        "locale_plan_heading": "После одобрения также расширить на эти языки",
        "locale_included_tag": "Уже включён",
        "locale_plan_hint": "Отмеченные языки здесь не проверяются построчно — последующий прогон локализации добавит их по этой же причине, без повторного одобрения.",
    },
    "fr": {
        "section_production": "1 · Site de production",
        "section_scope": "2 · Périmètres de sujets en attente de revue (point de contact 1)",
        "section_release": "3 · Publications en attente d'approbation (point de contact 2)",
        "section_panels": "4 · Panneaux privés locaux",
        "open_production": "Ouvrir le site de production ↗",
        "topic_count_page_count": "{topics} sujets · {pages} pages",
        "build_date": "Construit le {value}",
        "chrome_version": "chrome {value}",
        "production_missing": "L'arborescence de production n'existe pas encore ; reconstruisez-la selon packages/publish/README.md.",
        "release_empty": "Aucun candidat n'attend d'approbation. Générez-en un avec <code>review-preview</code>, puis montez-le avec <code>dev-serve --preview &lt;dir&gt;</code>.",
        "release_none_pending": "Aucun candidat en attente de décision.",
        "approve_all": "Approuver et autoriser les {n} d'un coup…",
        "approve_all_hint": "La même raison est écrite pour chacun ; utilisez le bouton de chaque carte pour décider individuellement.",
        "approve_all_confirm_prefix": "Ceci écrira les deux enregistrements ci-dessus pour chacun de : ",
        "reason_placeholder_each": "Raison (obligatoire — conservée en permanence avec l'événement)",
        "reason_placeholder_all": "Raison (obligatoire — conservée en permanence avec chaque événement)",
        "confirm_all": "Confirmer tout",
        "cancel": "Annuler",
        "tag_live": "En ligne",
        "release_live_note": "Les octets de cet aperçu sont déjà ceux en ligne ; il n'y a rien à décider. Version en ligne {publication_id}.",
        "release_no_review_locale": "Le fichier <code>topic_manifest.yaml</code> de ce sujet ne nomme aucune langue de révision : il n'existe donc aucune version à laquelle rattacher une approbation. Renseignez <code>review_locale</code> dans le scope, puis rechargez.",
        "release_review_locale_absent": "Cet aperçu ne contient aucune page en {locale}, la langue de révision de ce sujet. Régénérez le candidat dans cette langue avant d'approuver.",
        "target_supersede": "remplacer la version actuellement en ligne {publication_id}",
        "target_first": "devenir la <strong>première</strong> version en ligne de ce sujet",
        "done_title": "Approuvé et autorisé à la publication",
        "done_record_label": "Enregistrement",
        "done_hint": "Ce qui reste est mécanique : verify-candidate reproduit les octets, puis un agent exécute activate. Un échec de vérification rejette automatiquement — rien n'est publié en silence.",
        "approve_release_btn": "Approuver et autoriser…",
        "write_note_btn": "Écrire une note de relecture (pas une approbation)",
        "confirm_records": "Confirmer écrit d'un coup <strong>deux enregistrements</strong> : un <code>PublicationReview</code> par langue (liant les octets exacts ci-dessus), et un <code>HumanApproval</code> autorisant ce candidat à ",
        "confirm_kept_history": "L'ancienne version n'est pas supprimée — elle devient l'historique ; la chaîne d'événements enregistre ce remplacement.",
        "confirm_not_immediate": "<strong>Toujours pas publié immédiatement</strong> : le candidat doit d'abord passer la comparaison de re-rendu de <code>verify-candidate</code> — tout octet différent le rejette automatiquement.",
        "confirm_approve_btn": "Confirmer l'approbation et l'autorisation",
        "new_page": "Nouvelle page",
        "diff_from_live": "Diffère de la version en ligne",
        "same_as_live": "Identique à la version en ligne",
        "bytes_approved": "Octets approuvés",
        "read_locale_link": "Lire {locale} ↗",
        "candidate_hash_label": "candidat {hash}",
        "live_hash_label": "en ligne {hash}",
        "page_run_label": "page run {value}",
        "theme_label": "thème {value}",
        "theme_none": "—",
        "categories_label": "catégories {value}",
        "categories_none": "aucune proposée",
        "prepared_label": "préparé {id}",
        "not_prepared_label": "pas encore préparé",
        "tag_unsigned": "En attente de signature",
        "sign_in_browser_btn": "Signer le point de contact 1 dans le navigateur",
        "scope_empty": "Aucun périmètre de sujet en attente de signature. ({n} déjà signés ; les sujets signés ne sont pas listés.)",
        "scope_more_signed": "{n} de plus déjà signés, non listés.",
        "panels_hint": "Généré par un script local et visible uniquement sur cette machine : jamais déployé, jamais commité, et ne constitue les octets de revue d'aucune publication.",
        "form_groups": "Les deux groupes",
        "form_include": "Dans le périmètre",
        "form_exclude": "Hors périmètre",
        "form_seeds": "Questions de départ",
        "form_required": "Obligatoire (annotate doit la couvrir)",
        "form_note_placeholder": "Note de signature (facultatif)",
        "form_submit": "Signer le point de contact 1",
        "form_no_candidates": "Ce sujet n'a pas de scope/question_candidates.yaml ; la signature n'écrit que le scope_approval du manifeste.",
        "form_window": "Fenêtre {start} → {end} · risque {risk}",
        "form_ongoing": "en cours",
        "js_reason_required_each": "Une raison est obligatoire : elle est conservée en permanence avec l'événement.",
        "js_reason_required_all": "Une raison est obligatoire : elle est conservée en permanence avec chaque événement.",
        "js_approved_authorized": "Approuvé et autorisé {path}. Pas encore publié.",
        "js_not_approved": "Non approuvé : {error}",
        "js_authorized_n_failed_m": "Autorisé {done}, échoué {failed} — {detail}",
        "js_approved_all": "Approuvé et autorisé {n}. Pas encore publié.",
        "js_note_prompt": "Note de relecture / raison de rejet (juste un enregistrement — ne change rien) :",
        "js_note_recorded": "Enregistré {path}",
        "js_failed": "Échec : {error}",
        "js_scope_signed": "Le point de contact 1 est signé — rechargez pour le voir.",
        "js_scope_not_signed": "Non signé : {detail}",
        "theme_button_label": "Basculer entre le mode clair et sombre",
        "language_button_label": "Changer la langue de l'interface",
        "locale_plan_heading": "Étendre aussi à ces langues après approbation",
        "locale_included_tag": "Déjà inclus",
        "locale_plan_hint": "Les langues cochées ne sont pas relues ici : une exécution de localisation ultérieure les ajoutera sous ce même motif, sans nouvelle approbation.",
    },
    "ko": {
        "section_production": "1 · 프로덕션 사이트",
        "section_scope": "2 · 검토 대기 중인 주제 범위 (접점 1)",
        "section_release": "3 · 승인 대기 중인 릴리스 (접점 2)",
        "section_panels": "4 · 로컬 비공개 패널",
        "open_production": "프로덕션 사이트 열기 ↗",
        "topic_count_page_count": "주제 {topics}개 · 페이지 {pages}개",
        "build_date": "빌드일 {value}",
        "chrome_version": "chrome {value}",
        "production_missing": "프로덕션 트리가 아직 없습니다. packages/publish/README.md에 따라 다시 빌드하세요.",
        "release_empty": "승인을 기다리는 후보가 없습니다. <code>review-preview</code>로 하나를 렌더링한 뒤 <code>dev-serve --preview &lt;dir&gt;</code>로 연결하세요.",
        "release_none_pending": "결정을 기다리는 후보가 없습니다.",
        "approve_all": "{n}개 전체를 한 번에 승인 및 권한 부여…",
        "approve_all_hint": "동일한 사유가 모든 항목에 기록됩니다. 개별적으로 결정하려면 각 카드의 버튼을 사용하세요.",
        "approve_all_confirm_prefix": "다음 각 주제에 대해 위의 두 기록을 각각 작성합니다: ",
        "reason_placeholder_each": "사유 (필수 — 이벤트와 함께 영구 보관됨)",
        "reason_placeholder_all": "사유 (필수 — 각 이벤트와 함께 영구 보관됨)",
        "confirm_all": "전체 확인",
        "cancel": "취소",
        "tag_live": "게시됨",
        "release_live_note": "이 미리보기의 바이트는 이미 게시된 바이트와 같습니다. 결정할 사항이 없습니다. 현재 게시 버전 {publication_id}.",
        "release_no_review_locale": "이 주제의 <code>topic_manifest.yaml</code>에 검수 언어가 없어 승인을 묶을 렌더링이 없습니다. scope에 <code>review_locale</code>을 지정한 뒤 새로고침하세요.",
        "release_review_locale_absent": "이 미리보기에는 {locale} 페이지가 없습니다 — 이 주제의 검수 언어입니다. 승인 전에 해당 언어로 후보를 다시 렌더링하세요.",
        "target_supersede": "현재 게시된 버전 {publication_id}을(를) 대체합니다",
        "target_first": "이 주제의 <strong>첫 번째</strong> 게시 버전이 됩니다",
        "done_title": "승인 및 게시 권한 부여됨",
        "done_record_label": "기록",
        "done_hint": "남은 일은 기계가 처리합니다: verify-candidate가 바이트를 재현하고, 이후 에이전트가 activate를 실행합니다. 검증에 실패하면 자동으로 반려되며, 조용히 게시되는 일은 없습니다.",
        "approve_release_btn": "승인 및 게시 권한 부여…",
        "write_note_btn": "검토 의견 작성 (승인 아님)",
        "confirm_records": "확인을 누르면 <strong>두 개의 기록</strong>이 한 번에 작성됩니다: 언어별 <code>PublicationReview</code> 하나(위의 정확한 바이트에 연결됨)와, 이 후보를 승인하는 <code>HumanApproval</code> 하나가 ",
        "confirm_kept_history": "이전 버전은 삭제되지 않고 이력으로 남습니다. 이벤트 체인에 이번 교체가 기록됩니다.",
        "confirm_not_immediate": "<strong>그래도 즉시 게시되지는 않습니다</strong>: 후보는 먼저 <code>verify-candidate</code>의 재렌더링 비교를 통과해야 하며, 바이트가 하나라도 다르면 자동으로 반려됩니다.",
        "confirm_approve_btn": "승인 및 권한 부여 확인",
        "new_page": "새 페이지",
        "diff_from_live": "게시된 버전과 다름",
        "same_as_live": "게시된 버전과 동일",
        "bytes_approved": "바이트 승인됨",
        "read_locale_link": "{locale} 읽기 ↗",
        "candidate_hash_label": "후보 {hash}",
        "live_hash_label": "게시됨 {hash}",
        "page_run_label": "page run {value}",
        "theme_label": "테마 {value}",
        "theme_none": "—",
        "categories_label": "분류 {value}",
        "categories_none": "제안 없음",
        "prepared_label": "prepare 완료 {id}",
        "not_prepared_label": "아직 prepare 안 됨",
        "tag_unsigned": "서명 대기",
        "sign_in_browser_btn": "브라우저에서 접점 1 서명하기",
        "scope_empty": "서명을 기다리는 주제 범위가 없습니다. (이미 {n}개 서명됨. 서명된 항목은 표시되지 않습니다.)",
        "scope_more_signed": "이미 서명된 {n}개가 더 있으며, 표시되지 않습니다.",
        "panels_hint": "로컬 스크립트로 생성되었으며 이 컴퓨터에서만 보입니다. 배포되지 않고, 커밋되지 않으며, 어떤 게시물의 검토 바이트도 아닙니다.",
        "form_groups": "두 그룹",
        "form_include": "범위 내",
        "form_exclude": "범위 외",
        "form_seeds": "질문 시드",
        "form_required": "필수 (annotate가 반드시 다뤄야 함)",
        "form_note_placeholder": "서명 메모 (선택 사항)",
        "form_submit": "접점 1 서명하기",
        "form_no_candidates": "이 주제에는 scope/question_candidates.yaml이 없습니다. 서명은 매니페스트의 scope_approval만 기록합니다.",
        "form_window": "기간 {start} → {end} · 위험도 {risk}",
        "form_ongoing": "진행 중",
        "js_reason_required_each": "사유는 필수입니다: 이벤트와 함께 영구 보관됩니다.",
        "js_reason_required_all": "사유는 필수입니다: 각 이벤트와 함께 영구 보관됩니다.",
        "js_approved_authorized": "{path} 승인 및 권한 부여됨. 아직 게시되지 않았습니다.",
        "js_not_approved": "승인되지 않음: {error}",
        "js_authorized_n_failed_m": "{done}개 권한 부여, {failed}개 실패 — {detail}",
        "js_approved_all": "{n}개 승인 및 권한 부여됨. 아직 게시되지 않았습니다.",
        "js_note_prompt": "검토 의견 / 반려 사유 (단순 기록이며 아무 상태도 변경하지 않습니다):",
        "js_note_recorded": "{path} 기록됨",
        "js_failed": "실패: {error}",
        "js_scope_signed": "접점 1이 서명되었습니다 — 새로고침하여 확인하세요.",
        "js_scope_not_signed": "서명되지 않음: {detail}",
        "theme_button_label": "밝은/어두운 테마 전환",
        "language_button_label": "인터페이스 언어 전환",
        "locale_plan_heading": "승인 후 이 언어들로도 확장",
        "locale_included_tag": "이미 포함됨",
        "locale_plan_hint": "체크한 언어는 여기서 한 줄씩 검토하지 않습니다 — 이후 현지화 실행이 같은 사유로 보완하며, 두 번째 승인은 필요하지 않습니다.",
    },
    "hi": {
        "section_production": "1 · प्रोडक्शन साइट",
        "section_scope": "2 · समीक्षा हेतु लंबित विषय दायरे (टचपॉइंट 1)",
        "section_release": "3 · अनुमोदन हेतु लंबित रिलीज़ (टचपॉइंट 2)",
        "section_panels": "4 · स्थानीय निजी पैनल",
        "open_production": "प्रोडक्शन साइट खोलें ↗",
        "topic_count_page_count": "{topics} विषय · {pages} पृष्ठ",
        "build_date": "बिल्ड तिथि {value}",
        "chrome_version": "chrome {value}",
        "production_missing": "प्रोडक्शन ट्री अभी मौजूद नहीं है; इसे packages/publish/README.md के अनुसार फिर से बनाएँ।",
        "release_empty": "अनुमोदन के लिए कोई उम्मीदवार लंबित नहीं है। <code>review-preview</code> से एक बनाएँ, फिर <code>dev-serve --preview &lt;dir&gt;</code> से जोड़ें।",
        "release_none_pending": "निर्णय के लिए कोई उम्मीदवार लंबित नहीं है।",
        "approve_all": "सभी {n} को एक साथ अनुमोदित और अधिकृत करें…",
        "approve_all_hint": "हर एक के लिए एक ही कारण लिखा जाएगा; अलग-अलग तय करने के लिए नीचे प्रत्येक का अपना बटन उपयोग करें।",
        "approve_all_confirm_prefix": "इससे ऊपर दिए गए दोनों रिकॉर्ड निम्नलिखित प्रत्येक विषय के लिए लिखे जाएँगे: ",
        "reason_placeholder_each": "कारण (आवश्यक — घटना के साथ स्थायी रूप से रखा जाएगा)",
        "reason_placeholder_all": "कारण (आवश्यक — हर घटना के साथ स्थायी रूप से रखा जाएगा)",
        "confirm_all": "सभी की पुष्टि करें",
        "cancel": "रद्द करें",
        "tag_live": "लाइव",
        "release_live_note": "इस पूर्वावलोकन के बाइट पहले से ही लाइव बाइट हैं; तय करने के लिए कुछ नहीं है। लाइव संस्करण {publication_id}।",
        "release_no_review_locale": "इस विषय की <code>topic_manifest.yaml</code> में समीक्षा भाषा नहीं दी गई है, इसलिए स्वीकृति को किसी रेंडरिंग से नहीं जोड़ा जा सकता। scope में <code>review_locale</code> भरें और पेज दोबारा लोड करें।",
        "release_review_locale_absent": "इस प्रीव्यू में {locale} का कोई पेज नहीं है — इसी भाषा में यह विषय समीक्षित होता है। स्वीकृति से पहले उम्मीदवार को उस भाषा में फिर से रेंडर करें।",
        "target_supersede": "वर्तमान लाइव संस्करण {publication_id} को प्रतिस्थापित करें",
        "target_first": "इस विषय का <strong>पहला</strong> लाइव संस्करण बनें",
        "done_title": "अनुमोदित और प्रकाशन हेतु अधिकृत",
        "done_record_label": "रिकॉर्ड",
        "done_hint": "बाकी काम मशीन का है: verify-candidate बाइट्स को दोबारा उत्पन्न करता है, फिर एक एजेंट activate चलाता है। सत्यापन विफल होने पर स्वतः अस्वीकृत हो जाता है — कुछ भी चुपचाप प्रकाशित नहीं होता।",
        "approve_release_btn": "अनुमोदित और अधिकृत करें…",
        "write_note_btn": "समीक्षा टिप्पणी लिखें (अनुमोदन नहीं)",
        "confirm_records": "पुष्टि करने पर एक साथ <strong>दो रिकॉर्ड</strong> लिखे जाते हैं: प्रत्येक भाषा के लिए एक <code>PublicationReview</code> (ऊपर दिए गए सटीक बाइट्स से जुड़ा हुआ), और एक <code>HumanApproval</code>, जो इस उम्मीदवार को ",
        "confirm_kept_history": "पुराना संस्करण हटाया नहीं जाता — यह इतिहास बन जाता है; इवेंट चेन इस प्रतिस्थापन को दर्ज करती है।",
        "confirm_not_immediate": "<strong>फिर भी तुरंत प्रकाशित नहीं होगा</strong>: उम्मीदवार को पहले <code>verify-candidate</code> की पुनः-रेंडर तुलना पास करनी होगी — कोई भी बेमेल बाइट इसे स्वतः अस्वीकृत कर देगा।",
        "confirm_approve_btn": "अनुमोदन और अधिकार की पुष्टि करें",
        "new_page": "नया पृष्ठ",
        "diff_from_live": "लाइव से भिन्न",
        "same_as_live": "लाइव के समान",
        "bytes_approved": "बाइट्स अनुमोदित",
        "read_locale_link": "{locale} पढ़ें ↗",
        "candidate_hash_label": "उम्मीदवार {hash}",
        "live_hash_label": "लाइव {hash}",
        "page_run_label": "page run {value}",
        "theme_label": "थीम {value}",
        "theme_none": "—",
        "categories_label": "श्रेणियाँ {value}",
        "categories_none": "कोई प्रस्तावित नहीं",
        "prepared_label": "prepare हुआ {id}",
        "not_prepared_label": "अभी prepare नहीं हुआ",
        "tag_unsigned": "हस्ताक्षर लंबित",
        "sign_in_browser_btn": "ब्राउज़र में टचपॉइंट 1 पर हस्ताक्षर करें",
        "scope_empty": "हस्ताक्षर हेतु कोई विषय दायरा लंबित नहीं है। ({n} पहले ही हस्ताक्षरित; हस्ताक्षरित विषय सूचीबद्ध नहीं किए जाते।)",
        "scope_more_signed": "{n} और पहले से हस्ताक्षरित हैं, सूचीबद्ध नहीं।",
        "panels_hint": "एक स्थानीय स्क्रिप्ट द्वारा जनरेट किया गया और केवल इसी मशीन पर दिखाई देता है: कभी डिप्लॉय नहीं होता, कभी कमिट नहीं होता, और यह किसी भी प्रकाशन के समीक्षा बाइट्स नहीं है।",
        "form_groups": "दोनों समूह",
        "form_include": "दायरे में",
        "form_exclude": "दायरे से बाहर",
        "form_seeds": "प्रश्न बीज",
        "form_required": "अनिवार्य (annotate को इसे कवर करना होगा)",
        "form_note_placeholder": "हस्ताक्षर टिप्पणी (वैकल्पिक)",
        "form_submit": "टचपॉइंट 1 पर हस्ताक्षर करें",
        "form_no_candidates": "इस विषय के पास scope/question_candidates.yaml नहीं है; हस्ताक्षर केवल मैनिफेस्ट का scope_approval लिखेगा।",
        "form_window": "अवधि {start} → {end} · जोखिम {risk}",
        "form_ongoing": "जारी",
        "js_reason_required_each": "कारण आवश्यक है: यह घटना के साथ स्थायी रूप से रखा जाता है।",
        "js_reason_required_all": "कारण आवश्यक है: यह हर घटना के साथ स्थायी रूप से रखा जाता है।",
        "js_approved_authorized": "{path} अनुमोदित और अधिकृत। अभी तक प्रकाशित नहीं हुआ।",
        "js_not_approved": "अनुमोदित नहीं: {error}",
        "js_authorized_n_failed_m": "{done} अधिकृत, {failed} विफल — {detail}",
        "js_approved_all": "{n} अनुमोदित और अधिकृत। अभी तक प्रकाशित नहीं हुआ।",
        "js_note_prompt": "समीक्षा टिप्पणी / अस्वीकृति कारण (यह केवल एक रिकॉर्ड है — कुछ भी नहीं बदलता):",
        "js_note_recorded": "{path} दर्ज किया गया",
        "js_failed": "विफल: {error}",
        "js_scope_signed": "टचपॉइंट 1 पर हस्ताक्षर हो चुका है — देखने के लिए पुनः लोड करें।",
        "js_scope_not_signed": "हस्ताक्षरित नहीं: {detail}",
        "theme_button_label": "हल्की / गहरी थीम के बीच स्विच करें",
        "language_button_label": "इंटरफ़ेस भाषा बदलें",
        "locale_plan_heading": "अनुमोदन के बाद इन भाषाओं में भी विस्तार करें",
        "locale_included_tag": "पहले से शामिल",
        "locale_plan_hint": "चुनी गई भाषाओं की यहाँ पंक्ति-दर-पंक्ति समीक्षा नहीं होती — बाद में एक स्थानीयकरण रन इसी कारण के तहत उन्हें पूरा करेगा, दोबारा अनुमोदन की आवश्यकता नहीं।",
    },
    "es": {
        "section_production": "1 · Sitio de producción",
        "section_scope": "2 · Alcances de temas pendientes de revisión (punto de contacto 1)",
        "section_release": "3 · Lanzamientos pendientes de aprobación (punto de contacto 2)",
        "section_panels": "4 · Paneles privados locales",
        "open_production": "Abrir el sitio de producción ↗",
        "topic_count_page_count": "{topics} temas · {pages} páginas",
        "build_date": "Compilado el {value}",
        "chrome_version": "chrome {value}",
        "production_missing": "El árbol de producción aún no existe; reconstrúyalo según packages/publish/README.md.",
        "release_empty": "No hay candidatos pendientes de aprobación. Renderice uno con <code>review-preview</code> y luego móntelo con <code>dev-serve --preview &lt;dir&gt;</code>.",
        "release_none_pending": "No hay candidatos pendientes de decisión.",
        "approve_all": "Aprobar y autorizar los {n} de una vez…",
        "approve_all_hint": "Se escribe el mismo motivo para cada uno; use el botón de cada tarjeta para decidir individualmente.",
        "approve_all_confirm_prefix": "Esto escribirá los dos registros anteriores para cada uno de: ",
        "reason_placeholder_each": "Motivo (obligatorio: se conserva permanentemente con el evento)",
        "reason_placeholder_all": "Motivo (obligatorio: se conserva permanentemente con cada evento)",
        "confirm_all": "Confirmar todo",
        "cancel": "Cancelar",
        "tag_live": "En línea",
        "release_live_note": "Los bytes de esta vista previa ya son los bytes en línea; no hay nada que decidir. Versión en línea {publication_id}.",
        "release_no_review_locale": "El archivo <code>topic_manifest.yaml</code> de este tema no indica el idioma de revisión, así que no hay una versión a la que vincular la aprobación. Define <code>review_locale</code> en el scope y recarga.",
        "release_review_locale_absent": "Esta vista previa no incluye ninguna página en {locale}, el idioma de revisión de este tema. Vuelve a generar el candidato en ese idioma antes de aprobar.",
        "target_supersede": "reemplazar la versión actualmente en línea {publication_id}",
        "target_first": "convertirse en la <strong>primera</strong> versión en línea de este tema",
        "done_title": "Aprobado y autorizado para publicar",
        "done_record_label": "Registro",
        "done_hint": "Lo que queda es mecánico: verify-candidate reproduce los bytes y luego un agente ejecuta activate. Una verificación fallida rechaza automáticamente; nada se publica en silencio.",
        "approve_release_btn": "Aprobar y autorizar…",
        "write_note_btn": "Escribir una nota de revisión (no una aprobación)",
        "confirm_records": "Confirmar escribe de una vez <strong>dos registros</strong>: un <code>PublicationReview</code> por idioma (vinculado a los bytes exactos de arriba) y un <code>HumanApproval</code> que autoriza a este candidato a ",
        "confirm_kept_history": "La versión anterior no se elimina, se convierte en historial; la cadena de eventos registra este reemplazo.",
        "confirm_not_immediate": "<strong>Aún no se publica de inmediato</strong>: el candidato primero debe pasar la comparación de re-renderizado de <code>verify-candidate</code>; cualquier byte que no coincida lo rechaza automáticamente.",
        "confirm_approve_btn": "Confirmar aprobación y autorización",
        "new_page": "Página nueva",
        "diff_from_live": "Difiere de la versión en línea",
        "same_as_live": "Igual a la versión en línea",
        "bytes_approved": "Bytes aprobados",
        "read_locale_link": "Leer {locale} ↗",
        "candidate_hash_label": "candidato {hash}",
        "live_hash_label": "en línea {hash}",
        "page_run_label": "page run {value}",
        "theme_label": "tema {value}",
        "theme_none": "—",
        "categories_label": "categorías {value}",
        "categories_none": "ninguna propuesta",
        "prepared_label": "preparado {id}",
        "not_prepared_label": "aún no preparado",
        "tag_unsigned": "Pendiente de firma",
        "sign_in_browser_btn": "Firmar el punto de contacto 1 en el navegador",
        "scope_empty": "No hay alcances de tema pendientes de firma. ({n} ya firmados; los firmados no se listan.)",
        "scope_more_signed": "{n} más ya firmados, no listados.",
        "panels_hint": "Generado por un script local y visible solo en esta máquina: nunca se despliega, nunca se confirma (commit), y no son bytes de revisión de ninguna publicación.",
        "form_groups": "Los dos grupos",
        "form_include": "Dentro del alcance",
        "form_exclude": "Fuera del alcance",
        "form_seeds": "Preguntas semilla",
        "form_required": "Obligatoria (annotate debe cubrirla)",
        "form_note_placeholder": "Nota de firma (opcional)",
        "form_submit": "Firmar el punto de contacto 1",
        "form_no_candidates": "Este tema no tiene scope/question_candidates.yaml; firmar solo escribe el scope_approval del manifiesto.",
        "form_window": "Ventana {start} → {end} · riesgo {risk}",
        "form_ongoing": "en curso",
        "js_reason_required_each": "El motivo es obligatorio: se conserva permanentemente con el evento.",
        "js_reason_required_all": "El motivo es obligatorio: se conserva permanentemente con cada evento.",
        "js_approved_authorized": "Aprobado y autorizado {path}. Aún no publicado.",
        "js_not_approved": "No aprobado: {error}",
        "js_authorized_n_failed_m": "Autorizados {done}, fallidos {failed} — {detail}",
        "js_approved_all": "Aprobados y autorizados {n}. Aún no publicado.",
        "js_note_prompt": "Nota de revisión / motivo de rechazo (solo un registro, no cambia nada):",
        "js_note_recorded": "Registrado {path}",
        "js_failed": "Error: {error}",
        "js_scope_signed": "El punto de contacto 1 está firmado; recargue para verlo.",
        "js_scope_not_signed": "No firmado: {detail}",
        "theme_button_label": "Alternar entre modo claro y oscuro",
        "language_button_label": "Cambiar el idioma de la interfaz",
        "locale_plan_heading": "También expandir a estos idiomas tras la aprobación",
        "locale_included_tag": "Ya incluido",
        "locale_plan_hint": "Los idiomas marcados no se revisan línea por línea aquí — una ejecución de localización posterior los completará bajo este mismo motivo, sin una segunda aprobación.",
    },
    "ja": {
        "section_production": "1 · 本番サイト",
        "section_scope": "2 · レビュー待ちのトピック範囲（タッチポイント1）",
        "section_release": "3 · 承認待ちのリリース（タッチポイント2）",
        "section_panels": "4 · ローカル専用パネル",
        "open_production": "本番サイトを開く ↗",
        "topic_count_page_count": "トピック {topics} 件 · ページ {pages} 件",
        "build_date": "ビルド日 {value}",
        "chrome_version": "chrome {value}",
        "production_missing": "本番ツリーはまだ存在しません。packages/publish/README.md の手順に従って再構築してください。",
        "release_empty": "承認待ちの候補はありません。<code>review-preview</code> でひとつレンダリングし、<code>dev-serve --preview &lt;dir&gt;</code> でマウントしてください。",
        "release_none_pending": "判断待ちの候補はありません。",
        "approve_all": "{n} 件すべてを一括承認・許可…",
        "approve_all_hint": "同じ理由がすべてに記録されます。個別に判断する場合は各カードのボタンを使ってください。",
        "approve_all_confirm_prefix": "以下の各トピックについて、上記の2つの記録をそれぞれ書き込みます: ",
        "reason_placeholder_each": "理由（必須 — イベントとともに永久に保存されます）",
        "reason_placeholder_all": "理由（必須 — 各イベントとともに永久に保存されます）",
        "confirm_all": "すべて確認",
        "cancel": "キャンセル",
        "tag_live": "公開中",
        "release_live_note": "このプレビューのバイト列はすでに公開中のバイト列と同じです。判断することはありません。公開中バージョン {publication_id}。",
        "release_no_review_locale": "この議題の <code>topic_manifest.yaml</code> に審査言語が書かれていないため、承認を結び付ける版がありません。scope に <code>review_locale</code> を設定して再読み込みしてください。",
        "release_review_locale_absent": "このプレビューには {locale} のページがありません——この議題の審査言語です。承認の前にその言語で候補を再レンダリングしてください。",
        "target_supersede": "現在公開中のバージョン {publication_id} を置き換える",
        "target_first": "このトピックの<strong>最初の</strong>公開バージョンになる",
        "done_title": "承認・公開許可済み",
        "done_record_label": "記録",
        "done_hint": "残りは機械的な処理です。verify-candidate がバイト列を再現し、その後エージェントが activate を実行します。検証に失敗すると自動的に差し戻され、静かに公開されることはありません。",
        "approve_release_btn": "承認して公開を許可…",
        "write_note_btn": "レビュー意見を書く（承認ではない）",
        "confirm_records": "確認すると、<strong>2種類の記録</strong>が一度に書き込まれます。上記の正確なバイト列に紐づく言語ごとの <code>PublicationReview</code> と、この候補に対して",
        "confirm_kept_history": "旧バージョンは削除されず、履歴として残ります。イベントチェーンにこの置き換えが記録されます。",
        "confirm_not_immediate": "<strong>それでも即座には公開されません</strong>: 候補はまず <code>verify-candidate</code> の再レンダリング比較を通過する必要があり、1バイトでも一致しなければ自動的に差し戻されます。",
        "confirm_approve_btn": "承認と許可を確定",
        "new_page": "新しいページ",
        "diff_from_live": "公開中と異なる",
        "same_as_live": "公開中と同じ",
        "bytes_approved": "バイト列承認済み",
        "read_locale_link": "{locale} を読む ↗",
        "candidate_hash_label": "候補 {hash}",
        "live_hash_label": "公開中 {hash}",
        "page_run_label": "page run {value}",
        "theme_label": "テーマ {value}",
        "theme_none": "—",
        "categories_label": "カテゴリー {value}",
        "categories_none": "提案なし",
        "prepared_label": "prepare 済み {id}",
        "not_prepared_label": "まだ prepare されていません",
        "tag_unsigned": "署名待ち",
        "sign_in_browser_btn": "ブラウザでタッチポイント1に署名する",
        "scope_empty": "署名待ちのトピック範囲はありません。（すでに {n} 件署名済み。署名済みは一覧に表示されません。）",
        "scope_more_signed": "ほかに {n} 件が署名済みで、一覧には表示されていません。",
        "panels_hint": "ローカルスクリプトによって生成され、このマシンでのみ表示されます。デプロイされず、コミットもされず、いかなる publication のレビューバイト列でもありません。",
        "form_groups": "2つのグループ",
        "form_include": "範囲内",
        "form_exclude": "範囲外",
        "form_seeds": "質問のシード",
        "form_required": "必須（annotate で必ずカバーすること）",
        "form_note_placeholder": "署名メモ（任意）",
        "form_submit": "タッチポイント1に署名する",
        "form_no_candidates": "このトピックには scope/question_candidates.yaml がありません。署名はマニフェストの scope_approval のみを書き込みます。",
        "form_window": "期間 {start} → {end} · リスク {risk}",
        "form_ongoing": "継続中",
        "js_reason_required_each": "理由は必須です: イベントとともに永久に保存されます。",
        "js_reason_required_all": "理由は必須です: 各イベントとともに永久に保存されます。",
        "js_approved_authorized": "{path} を承認・許可しました。まだ公開されていません。",
        "js_not_approved": "承認されませんでした: {error}",
        "js_authorized_n_failed_m": "{done} 件許可、{failed} 件失敗 — {detail}",
        "js_approved_all": "{n} 件を承認・許可しました。まだ公開されていません。",
        "js_note_prompt": "レビュー意見 / 差し戻し理由（単なる記録で、状態は変わりません）:",
        "js_note_recorded": "{path} を記録しました",
        "js_failed": "失敗: {error}",
        "js_scope_signed": "タッチポイント1は署名済みです — 再読み込みして確認してください。",
        "js_scope_not_signed": "未署名: {detail}",
        "theme_button_label": "ライト / ダークテーマを切り替える",
        "language_button_label": "インターフェース言語を切り替える",
        "locale_plan_heading": "承認後、これらの言語にも展開する",
        "locale_included_tag": "含まれています",
        "locale_plan_hint": "チェックした言語はここで逐語レビューされません — 後続のローカライズ実行が同じ理由のもとで補完し、二度目の承認は不要です。",
    },
    "ar": {
        "section_production": "1 · موقع الإنتاج",
        "section_scope": "2 · نطاقات المواضيع بانتظار المراجعة (نقطة التواصل 1)",
        "section_release": "3 · الإصدارات بانتظار الموافقة (نقطة التواصل 2)",
        "section_panels": "4 · لوحات خاصة محلية",
        "open_production": "فتح موقع الإنتاج ↗",
        "topic_count_page_count": "{topics} موضوعًا · {pages} صفحة",
        "build_date": "تاريخ البناء {value}",
        "chrome_version": "chrome {value}",
        "production_missing": "شجرة الإنتاج غير موجودة بعد؛ أعد بناءها وفق packages/publish/README.md.",
        "release_empty": "لا يوجد مرشحون بانتظار الموافقة. أنشئ واحدًا باستخدام <code>review-preview</code>، ثم اربطه باستخدام <code>dev-serve --preview &lt;dir&gt;</code>.",
        "release_none_pending": "لا يوجد مرشحون بانتظار قرار.",
        "approve_all": "الموافقة والتفويض لجميع الـ {n} دفعة واحدة…",
        "approve_all_hint": "يُكتب نفس السبب لكل عنصر؛ استخدم زر كل بطاقة للقرار الفردي.",
        "approve_all_confirm_prefix": "سيؤدي هذا إلى كتابة السجلَّين أعلاه لكل من: ",
        "reason_placeholder_each": "السبب (مطلوب — يُحفظ بشكل دائم مع الحدث)",
        "reason_placeholder_all": "السبب (مطلوب — يُحفظ بشكل دائم مع كل حدث)",
        "confirm_all": "تأكيد الكل",
        "cancel": "إلغاء",
        "tag_live": "منشور حاليًا",
        "release_live_note": "بايتات هذه المعاينة مطابقة بالفعل للبايتات المنشورة؛ لا يوجد ما يُقرَّر. النسخة المنشورة حاليًا {publication_id}.",
        "release_no_review_locale": "لا يذكر ملف <code>topic_manifest.yaml</code> لهذا الموضوع لغة المراجعة، فلا توجد نسخة يمكن ربط الموافقة بها. حدِّد <code>review_locale</code> في النطاق ثم أعد التحميل.",
        "release_review_locale_absent": "لا تتضمّن هذه المعاينة صفحة بلغة {locale}، وهي لغة مراجعة هذا الموضوع. أعد توليد النسخة المرشّحة بتلك اللغة قبل الموافقة.",
        "target_supersede": "استبدال النسخة المنشورة حاليًا {publication_id}",
        "target_first": "أن تصبح <strong>أول</strong> نسخة منشورة لهذا الموضوع",
        "done_title": "تمت الموافقة والتفويض بالنشر",
        "done_record_label": "السجل",
        "done_hint": "ما تبقّى هو عمل آلي: يعيد verify-candidate إنتاج البايتات، ثم ينفذ أحد الوكلاء activate. أي فشل في التحقق يُرفض تلقائيًا — لا يُنشر شيء بصمت.",
        "approve_release_btn": "الموافقة والتفويض بالنشر…",
        "write_note_btn": "كتابة ملاحظة مراجعة (وليست موافقة)",
        "confirm_records": "يؤدي التأكيد إلى كتابة <strong>سجلَّين</strong> دفعة واحدة: <code>PublicationReview</code> لكل لغة (مرتبط بالبايتات الدقيقة أعلاه)، و<code>HumanApproval</code> واحد يفوّض هذا المرشح بأن ",
        "confirm_kept_history": "لا يُحذف الإصدار القديم — بل يصبح سجلًا تاريخيًا؛ تُسجَّل سلسلة الأحداث هذا الاستبدال.",
        "confirm_not_immediate": "<strong>لا يُنشر فورًا مع ذلك</strong>: يجب أن يجتاز المرشح أولًا مقارنة إعادة العرض في <code>verify-candidate</code> — أي بايت غير مطابق يرفضه تلقائيًا.",
        "confirm_approve_btn": "تأكيد الموافقة والتفويض",
        "new_page": "صفحة جديدة",
        "diff_from_live": "يختلف عن النسخة المنشورة",
        "same_as_live": "مطابق للنسخة المنشورة",
        "bytes_approved": "تمت الموافقة على البايتات",
        "read_locale_link": "قراءة {locale} ↗",
        "candidate_hash_label": "المرشح {hash}",
        "live_hash_label": "المنشور {hash}",
        "page_run_label": "page run {value}",
        "theme_label": "السمة {value}",
        "theme_none": "—",
        "categories_label": "الفئات {value}",
        "categories_none": "لم يُقترح أي منها",
        "prepared_label": "تم التحضير {id}",
        "not_prepared_label": "لم يُحضَّر بعد",
        "tag_unsigned": "بانتظار التوقيع",
        "sign_in_browser_btn": "توقيع نقطة التواصل 1 في المتصفح",
        "scope_empty": "لا توجد نطاقات مواضيع بانتظار التوقيع. (تم توقيع {n} بالفعل؛ لا تُدرَج المواضيع الموقَّعة.)",
        "scope_more_signed": "يوجد {n} أخرى موقَّعة بالفعل، غير مدرَجة.",
        "panels_hint": "أُنشئت بواسطة سكربت محلي وتظهر فقط على هذا الجهاز: لا تُنشر أبدًا، ولا تُضاف إلى Git، وليست بايتات مراجعة لأي منشور.",
        "form_groups": "المجموعتان",
        "form_include": "ضمن النطاق",
        "form_exclude": "خارج النطاق",
        "form_seeds": "أسئلة أولية",
        "form_required": "إلزامي (يجب أن يغطيه annotate)",
        "form_note_placeholder": "ملاحظة التوقيع (اختياري)",
        "form_submit": "توقيع نقطة التواصل 1",
        "form_no_candidates": "لا يحتوي هذا الموضوع على scope/question_candidates.yaml؛ التوقيع يكتب فقط scope_approval الخاص بالبيان.",
        "form_window": "الفترة {start} → {end} · الخطورة {risk}",
        "form_ongoing": "مستمر",
        "js_reason_required_each": "السبب مطلوب: يُحفظ بشكل دائم مع الحدث.",
        "js_reason_required_all": "السبب مطلوب: يُحفظ بشكل دائم مع كل حدث.",
        "js_approved_authorized": "تمت الموافقة والتفويض {path}. لم يُنشر بعد.",
        "js_not_approved": "لم تتم الموافقة: {error}",
        "js_authorized_n_failed_m": "تم تفويض {done}، وفشل {failed} — {detail}",
        "js_approved_all": "تمت الموافقة والتفويض لـ {n}. لم يُنشر بعد.",
        "js_note_prompt": "ملاحظة مراجعة / سبب الرفض (مجرد سجل — لا يغيّر أي شيء):",
        "js_note_recorded": "تم تسجيل {path}",
        "js_failed": "فشل: {error}",
        "js_scope_signed": "تم توقيع نقطة التواصل 1 — أعد التحميل لرؤيته.",
        "js_scope_not_signed": "لم يُوقَّع: {detail}",
        "theme_button_label": "التبديل بين الوضع الفاتح والداكن",
        "language_button_label": "تبديل لغة الواجهة",
        "locale_plan_heading": "التوسّع أيضًا إلى هذه اللغات بعد الموافقة",
        "locale_included_tag": "مُدرَج بالفعل",
        "locale_plan_hint": "اللغات المحدَّدة لا تُراجَع هنا سطرًا بسطر — سيُكمِلها لاحقًا تشغيل توطين ضمن السبب نفسه، دون الحاجة إلى موافقة ثانية.",
    },
}

_expected_keys = set(_STRINGS[DEFAULT_DASHBOARD_LOCALE])
_expected_locales = set(HALO_LOCALE_CODES)
if set(_STRINGS) != _expected_locales:
    _missing_locales = sorted(_expected_locales - set(_STRINGS))
    _extra_locales = sorted(set(_STRINGS) - _expected_locales)
    raise RuntimeError(
        f"dashboard_strings does not cover exactly HALO_LOCALE_CODES: "
        f"missing={_missing_locales}, extra={_extra_locales}"
    )
for _locale in _STRINGS:
    if set(_STRINGS[_locale]) != _expected_keys:
        _missing = sorted(_expected_keys - set(_STRINGS[_locale]))
        _extra = sorted(set(_STRINGS[_locale]) - _expected_keys)
        raise RuntimeError(
            f"asymmetric dashboard dictionary for {_locale}: missing={_missing}, extra={_extra}"
        )


def dashboard_strings(locale: str) -> Mapping[str, str]:
    """Return immutable dashboard copy; unsupported locales fail instead of half-localizing."""
    canonical = normalize_lang(locale)
    try:
        return MappingProxyType(_STRINGS[canonical])
    except KeyError as exc:
        raise ValueError(f"unsupported dashboard locale: {canonical}") from exc
